CREATE TABLE [dbo].[Emails]
(
	[IdRecord] INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	[Subject] NVARCHAR(256) NOT NULL,
	[Message] NVARCHAR(256) NOT NULL DEFAULT '',
	[To] NVARCHAR(50) NOT NULL,
	[DateCreate] DATETIME NOT NULL DEFAULT GETDATE(),
	[DateSend] DATETIME NULL
)
