<?xml version="1.0" encoding="utf-8"?><Database Name="u0103018_partycafe" Class="PartyCafeClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=37.140.192.61;Initial Catalog=u0103018_partycafe;Persist Security Info=True;User ID=u0103018_partycafe_user" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="u0103018_partycafeConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Events" Member="Events">
    <Type Name="Events">
      <Column Name="IdRecord" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EventDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IdPhoto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserCreate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserUpdate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Photos_Events" Member="Photos" ThisKey="IdPhoto" OtherKey="IdRecord" Type="Photos" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Gallery" Member="Gallery">
    <Type Name="Gallery">
      <Column Name="IdRecord" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IdPhoto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="UserCreate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserUpdate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Photos_Gallery" Member="Photos" ThisKey="IdPhoto" OtherKey="IdRecord" Type="Photos" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Games" Member="Games">
    <Type Name="Games">
      <Column Name="IdRecord" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Platform" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="IdPhoto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserCreate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserUpdate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Photos_Games" Member="Photos" ThisKey="IdPhoto" OtherKey="IdRecord" Type="Photos" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="Users">
      <Column Name="IdRecord" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserCreate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserUpdate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Photos" Member="Photos">
    <Type Name="Photos">
      <Column Name="IdRecord" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FileName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Path" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="UserCreate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserUpdate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Photos_Events" Member="Events" ThisKey="IdRecord" OtherKey="IdPhoto" Type="Events" />
      <Association Name="Photos_Gallery" Member="Gallery" ThisKey="IdRecord" OtherKey="IdPhoto" Type="Gallery" />
      <Association Name="Photos_Games" Member="Games" ThisKey="IdRecord" OtherKey="IdPhoto" Type="Games" />
      <Association Name="Photos_MenuGroups" Member="MenuGroups" ThisKey="IdRecord" OtherKey="IdPhoto" Type="MenuGroups" />
      <Association Name="Photos_MenuItems" Member="MenuItems" ThisKey="IdRecord" OtherKey="IdPhoto" Type="MenuItems" />
      <Association Name="Photos_Services" Member="Services" ThisKey="IdRecord" OtherKey="IdPhoto" Type="Services" />
      <Association Name="Photos_ServicePhotos" Member="ServicePhotos" ThisKey="IdRecord" OtherKey="IdPhoto" Type="ServicePhotos" />
    </Type>
  </Table>
  <Table Name="dbo.MenuGroups" Member="MenuGroups">
    <Type Name="MenuGroups">
      <Column Name="IdRecord" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GroupName" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="IdParent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserCreate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserUpdate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IdPhoto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="MenuGroups_MenuGroups" Member="MenuGroups2" ThisKey="IdRecord" OtherKey="IdParent" Type="MenuGroups" />
      <Association Name="MenuGroups_MenuItems" Member="MenuItems" ThisKey="IdRecord" OtherKey="IdGroup" Type="MenuItems" />
      <Association Name="MenuGroups_MenuGroups" Member="MenuGroups1" ThisKey="IdParent" OtherKey="IdRecord" Type="MenuGroups" IsForeignKey="true" />
      <Association Name="Photos_MenuGroups" Member="Photos" ThisKey="IdPhoto" OtherKey="IdRecord" Type="Photos" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MenuItems" Member="MenuItems">
    <Type Name="MenuItems">
      <Column Name="IdRecord" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="IdPhoto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="Country" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Platform" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="UserCreate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserUpdate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IdGroup" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="MenuGroups_MenuItems" Member="MenuGroups" ThisKey="IdGroup" OtherKey="IdRecord" Type="MenuGroups" IsForeignKey="true" />
      <Association Name="Photos_MenuItems" Member="Photos" ThisKey="IdPhoto" OtherKey="IdRecord" Type="Photos" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="u0103018_partycafe_user.Services" Member="Services">
    <Type Name="Services">
      <Column Name="IdRecord" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="IdPhoto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="UserCreate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserUpdate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DateCreate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DateUpdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Services_ServicePhotos" Member="ServicePhotos" ThisKey="IdRecord" OtherKey="IdService" Type="ServicePhotos" />
      <Association Name="Photos_Services" Member="Photos" ThisKey="IdPhoto" OtherKey="IdRecord" Type="Photos" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="u0103018_partycafe_user.ServicePhotos" Member="ServicePhotos">
    <Type Name="ServicePhotos">
      <Column Name="IdRecord" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdService" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdPhoto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="Photos_ServicePhotos" Member="Photos" ThisKey="IdPhoto" OtherKey="IdRecord" Type="Photos" IsForeignKey="true" />
      <Association Name="Services_ServicePhotos" Member="Services" ThisKey="IdService" OtherKey="IdRecord" Type="Services" IsForeignKey="true" />
    </Type>
  </Table>
</Database>